apiVersion: v1
kind: Secret
metadata:
  name: voting-app-secrets
  namespace: {{ .Values.global.namespace | default "voting-app" }}
type: Opaque
data:
  postgres-password: {{ "voting_password" | b64enc | quote }}
  postgres-user: {{ "voting_user" | b64enc | quote }}
  postgres-db: {{ "voting_app" | b64enc | quote }}
